version: '2'
services:
  storage-postgres:
    image: busybox
    volumes:
      - /var/lib/postgresql/data
  storage-mysql:
    image: busybox
    volumes:
      - /var/lib/mysql

  postgres:
    image: postgres:9.6-alpine
    volumes_from:
      - storage-postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "cyqldog"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "cyqldogdb"
  mysql:
    image: mysql:5.6
    volumes_from:
      - storage-mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_USER: "cyqldog"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "cyqldogdb"
  dogstatsd:
    image: datadog/docker-dd-agent:11.0.5141-dogstatsd-alpine
    ports:
      - "8125:8125/udp"
    environment:
      DD_API_KEY: "${DD_API_KEY}"

  # For Dockerfile test
  # cyqldog:
  #   build: .
  #   command: ["bin/cyqldog", "-C", "config/local.yml"]
  #   links:
  #     - postgres:postgres
  #     - dogstatsd:dogstatsd
  #   environment:
  #     DB_HOST: "postgres"
  #     DB_PASSWORD: "${DB_PASSWORD}"
  #     DD_HOST: "dogstatsd"
  #     DD_API_KEY: "${DD_API_KEY}"
