version: 2
jobs:
  build:
    docker:
      - image: cimg/go:1.17.6

    steps:
      - checkout
      - run:
          name: Checking golang version
          command: go version
      - restore_cache:
          name: Restoring cache - vendor
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install packages
          command: go mod download
      - run:
          name: Build
          command: go build -o bin/cyqldog
      - run:
          name: Test
          command: go test $(go list ./... | grep -v /vendor/)

      - save_cache:
          name: Saving cache - vendor
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
