version: 2
jobs:
  build:
    docker:
      - image: crowdworks/dep:latest
        environment:
          GOPATH: /go
    working_directory: /go/src/github.com/crowdworks/cyqldog
    steps:
      - checkout
      - run:
          name: Checking golang version
          command: go version
      - restore_cache:
          name: Restoring cache - vendor
          keys:
            - vendor-{{ checksum "Gopkg.toml" }}-{{ checksum "Gopkg.lock" }}
      - run:
          name: Install packages
          command: dep ensure
      - run:
          name: Build
          command: go build -o bin/cyqldog
      - run:
          name: Test
          command: go test $(go list ./... | grep -v /vendor/)

      - save_cache:
          name: Saving cache - vendor
          key: vendor-{{ checksum "Gopkg.toml" }}-{{ checksum "Gopkg.lock" }}
          paths:
            - "vendor"
