name: pinact check

permissions:
  contents: read

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - '.github/**'

jobs:
  pinact_check:
    runs-on: ubuntu-24.04-2core-arm64
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - uses: suzuki-shunsuke/pinact-action@49cbd6acd0dbab6a6be2585d1dbdaa43b4410133 # v1.0.0
        with:
          skip_push: 'true'
